### ISSUE TITLE
meta.yaml + catalog.yaml validation as CI

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/LEAP_template_feedstock#26]
Tracking an idea from [this discussion](https://github.com/leap-stc/proto_feedstock/pull/19#issuecomment-2057966256) with @andersy005. 

It would be super nice if we could have some simple checking of the yaml files as part of the CI in each feedstock repo

**Comment by andersy005** [comment]
@jbusecke, do you prefer porting over the code from https://github.com/leap-stc/data-management/blob/revamped-catalog/catalog/schema.py

into a standalone repo/package under `leap-stc/catalog-spec` or putting it under `https://github.com/leap-stc/leap-data-management-utils`

**Comment by jbusecke** [comment]
Ah good question. Lets for now put it into `https://github.com/leap-stc/leap-data-management-utils` I think there is a bunch more code from the template point of view that can be absorbed there.
